"""Add an fs_ prefix to database tables

Revision ID: 61d0dbf5f25d
Revises: aa8248284496
Create Date: 2016-05-17 16:11:21.819733

"""

# revision identifiers, used by Alembic.
revision = '61d0dbf5f25d'
down_revision = 'aa8248284496'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('files', 'fs_files')
    op.rename_table('downloads', 'fs_downloads')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('fs_downloads', 'downloads')
    op.rename_table('fs_files', 'files')
    ### end Alembic commands ###
